# -*- coding: utf-8 -*-
"""ch1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bWOIYQaQ1qoqSAPDh40LYOnHrdRDdzIQ
"""

#phrase-o-matic
import random #dizemos os python que usaremos funções aleatórias extras que não vem por padrão se não informarmos ele!

verbos=['correr','varrer','olhar','tocar','abraçar','jogar','bater'] #listas
adjetivos=['dourado','prateado','invisivel','esperto','bela','verde','grande','pequeno','ligeiro']
substantivos=['caneta','gato','professor','terra','bola','unicórnio','fada','sereia']
verbo = random.choice(verbos) #seleciona um elemento aleatório da lista criada verbos
adjetivo = random.choice(adjetivos)
substantivo = random.choice(substantivos)

frase = verbo + ' ' + adjetivo + ' ' + substantivo
print(frase)


#*o import diz ao python para usar funcionalidades integradaz trazendo o módulo random dele

ola=input('what') #podemos usar a funcionalidade input() para entrar com dados!
print(ola)

